/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ASCLIN_Shell_UART.h"
#include "User_RTOS.h"
#include "PORT_cfg.h"
#include "GPT12_Timer_Interrupt.h"

#include "PWR_SQ.h"
#include "Can_Cfg.h"
#include "I2C_cfg.h"
#include "Ifx_Console.h"
#include "Bsp.h"
//Function   Mode   Direction  Latch  Pull Up Pull Down Drive Strength

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void main_loop(void *arg);
void Pwr_SQgpio(void *arg);

uint32 sda=0;

static void logIna226Measurements(void);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    Port_Init();
    initGpt12Timer();

    initShellInterface();
    I2c_Init();
    sys_thread_new("task_app_PWR_SQ",task_app_PWR_SQ,NULL,configMINIMAL_STACK_SIZE,4);
    sys_thread_new("main_loop",main_loop,NULL,configMINIMAL_STACK_SIZE,4);
    //sys_thread_new("Can_Task",Can_Task,NULL,configMINIMAL_STACK_SIZE,4);
    vTaskStartScheduler();

    while(1)
    {
        sda++;

    }
}

#define MAX20087_REG_ID      0x02
#define MAX20087_REG_STAT1   0x03
#define MAX20087_REG_STAT2L  0x04
#define MAX20087_REG_STAT2H  0x05
static void checkMAX20087(void)
{
    uint8 id = 0, stat1 = 0, stat2l = 0, stat2h = 0;
    uint8 part;

    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x28, MAX20087_REG_ID, &id, 1);
    part = (id >> 4) & 0x3;
    if (part != MAX20087_PART_ID_MAX20087) {
        Ifx_Console_print("MAX20087 ID mismatch (0x%02X)\r\n", id);
        return;
    }

    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x28, MAX20087_REG_STAT1, &stat1, 1);
    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x28, MAX20087_REG_STAT2L, &stat2l, 1);
    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x28, MAX20087_REG_STAT2H, &stat2h, 1);

    if (stat1 & 0xBC) { // ISET/OVIN/UVIN/OVDD/UVDD
        Ifx_Console_print("MAX20087 STAT1 fault: 0x%02X\r\n", stat1);
    } else if ((stat2l | stat2h) != 0) { // TS/OC/OV/UV
        Ifx_Console_print("MAX20087 STAT2 fault: L=0x%02X H=0x%02X\r\n", stat2l, stat2h);
    } else {
        Ifx_Console_print("MAX20087(U7300) OK\r\n");
    }

    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x29, MAX20087_REG_ID, &id, 1);
    part = (id >> 4) & 0x3;
    if (part != MAX20087_PART_ID_MAX20087) {
        Ifx_Console_print("MAX20087 ID mismatch (0x%02X)\r\n", id);
        return;
    }

    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x29, MAX20087_REG_STAT1, &stat1, 1);
    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x29, MAX20087_REG_STAT2L, &stat2l, 1);
    I2CRead_MAX20087(&I2cConf_I2cCh0_MAX20087_ADDR_0x29, MAX20087_REG_STAT2H, &stat2h, 1);

    if (stat1 & 0xBC) { // ISET/OVIN/UVIN/OVDD/UVDD
        Ifx_Console_print("MAX20087 STAT1 fault: 0x%02X\r\n", stat1);
    } else if ((stat2l | stat2h) != 0) { // TS/OC/OV/UV
        Ifx_Console_print("MAX20087 STAT2 fault: L=0x%02X H=0x%02X\r\n", stat2l, stat2h);
    } else {
        Ifx_Console_print("MAX20087(U7301) OK\r\n");
    }
}
uint32 str;
void main_loop(void *arg)
{


    while(1)
    {
        str++;
        vTaskDelay(pdMS_TO_TICKS(5000));
        runShellInterface(); /* Run the application shell */
        logIna226Measurements();

        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

int i2c_read_status = 0;
int i2c_write_status = 0;
static void logIna226Measurements(void)
{

#if 1
    float32 current = 0;
    float32 voltage = 0;
    boolean currentResult = FALSE;
    boolean voltageResult = FALSE;

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_0);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH0 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH0 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_1);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH1 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH1 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_2);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH2 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH2 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_3);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH3 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH3 read failed\r\n");
    }
#endif

#if 1
    uint8 cmd[2] = {0x24, 0x00};
    uint8 rx[6];
    uint16 rawT = 0;
    float tempC = 0;

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_7); //ch select

    i2c_write_status=IfxI2c_I2c_write(I2cConf_I2cCh0_STS31A_ADDR_0x4A.Device, cmd, 2);
    vTaskDelay(pdMS_TO_TICKS(20));

    i2c_read_status=IfxI2c_I2c_read(I2cConf_I2cCh0_STS31A_ADDR_0x4A.Device, rx, 6);
    rawT = ((uint16)rx[0] << 8) | rx[1];
    tempC = -45.0f + (175.0f * (float)rawT / 65535.0f);

    Ifx_Console_print("STS31A TMON1 -> Temp: %.2f C\r\n", tempC);

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x71, TCA9548_Channel_0); //ch select

    i2c_write_status=IfxI2c_I2c_write(I2cConf_I2cCh0_STS31A_ADDR_0x4B.Device, cmd, 2);
    vTaskDelay(pdMS_TO_TICKS(20));

    i2c_read_status=IfxI2c_I2c_read(I2cConf_I2cCh0_STS31A_ADDR_0x4B.Device, rx, 6);
    rawT = ((uint16)rx[0] << 8) | rx[1];
    tempC = -45.0f + (175.0f * (float)rawT / 65535.0f);

    Ifx_Console_print("STS31A TMON2 -> Temp: %.2f C\r\n", tempC);
#endif


    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x71, TCA9548_Channel_1); //ch select
    checkMAX20087();

}


