/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ASCLIN_Shell_UART.h"
#include "User_RTOS.h"
#include "PORT_cfg.h"
#include "GPT12_Timer_Interrupt.h"

#include "PWR_SQ.h"
#include "Can_Cfg.h"
#include "I2C_cfg.h"
#include "Ifx_Console.h"                                                                            //Function   Mode   Direction  Latch  Pull Up Pull Down Drive Strength

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void main_loop(void *arg);
void Pwr_SQgpio(void *arg);

uint32 sda=0;

static void logIna226Measurements(void);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    Port_Init();
    initGpt12Timer();

    initShellInterface();
    I2c_Init();
    sys_thread_new("task_app_PWR_SQ",task_app_PWR_SQ,NULL,configMINIMAL_STACK_SIZE,4);
    sys_thread_new("main_loop",main_loop,NULL,configMINIMAL_STACK_SIZE,4);
    //sys_thread_new("Can_Task",Can_Task,NULL,configMINIMAL_STACK_SIZE,4);
    vTaskStartScheduler();

    while(1)
    {
        sda++;

    }
}
uint32 str;
void main_loop(void *arg)
{


    while(1)
    {
        str++;
        runShellInterface(); /* Run the application shell */
        logIna226Measurements();
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

static void logIna226Measurements(void)
{
    float32 current = 0;
    float32 voltage = 0;
    boolean currentResult = FALSE;
    boolean voltageResult = FALSE;

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_0);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH0 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH0 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_1);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH1 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH1 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_2);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH2 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH2 read failed\r\n");
    }

    TCA9548_Channel_Sel(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, TCA9548_Channel_3);
    currentResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Current, &current);
    voltageResult = Read_INA226_Current_Voltage(&I2cConf_I2cCh0_INA226_ADDR_0x40, INA226_Voltage, &voltage);

    if((currentResult == TRUE) && (voltageResult == TRUE))
    {
        Ifx_Console_print("INA226 CH3 -> Current: %.3f A, Voltage: %.3f V\r\n", current, voltage);
    }
    else
    {
        Ifx_Console_print("INA226 CH3 read failed\r\n");
    }



}


