/*
 * CAN.h
 *
 *  Created on: 2022. 11. 1.
 *      Author: USER
 */

#ifndef APPL_CAN_CAN_H_
#define APPL_CAN_CAN_H_


/********************************************************************************************************************
 * \file MCMCAN.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MCMCAN_H_
#define MCMCAN_H_ 1

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdio.h>
#include <string.h>
#include "Ifx_Types.h"
#include "IfxCpu_Irq.h"
#include "IfxPort.h"                                        /* For GPIO Port Pin Control                            */
#include "IfxCan_Can.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define DO_NOT_CARE_BUFFER_INDEX    (IfxCan_RxBufferId)0
#define DO_NOT_CARE_ID2_VALUE       (uint32)0
#define NUMBER_OF_STND_ID_FILTERS   8                           /* Define the number of standard ID filter elements  */
#define NUMBER_OF_EXTD_ID_FILTERS   4                           /* Define the number of extended ID filter elements  */
#define NUMBER_OF_FIFO_ELEMENTS     15                          /* Define the number of RX FIFO 0/1 elements         */
#define MAXIMUM_CAN_DATA_PAYLOAD    8                           // Define maximum classical CAN payload in 4-byte words //
#define NUMBER_OF_CAN_MESSAGES      25                          /* Define the number of CAN messages to be sent      */
#define MAXIMUM_CAN_FD_DATA_PAYLOAD 64                          /* Define maximum CAN FD payload in bytes            */
#define MAXIMUM_DATA_PAYLOAD_WORDS  MAXIMUM_CAN_FD_DATA_PAYLOAD
/*
#define CAN0_MESSAGE_ID              (uint32)0x100           // Message ID that will be used in arbitration phase    //
#define CAN1_MESSAGE_ID              (uint32)0x200           // Message ID that will be used in arbitration phase    //
#define CAN2_MESSAGE_ID              (uint32)0x300           // Message ID that will be used in arbitration phase    //
#define CAN3_MESSAGE_ID              (uint32)0x400           // Message ID that will be used in arbitration phase    //
#define CAN4_MESSAGE_ID              (uint32)0x500           // Message ID that will be used in arbitration phase    //
#define PORT13_PIN0                 0                       // LED1 used in TX ISR is connected to this pin         //
#define PORT13_PIN1                 1                       // LED2 used in RX ISR is connected to this pin         //
#define PORT13_PIN2                 2                       // LED1 used in TX ISR is connected to this pin         //
#define PORT13_PIN3                 3                       // LED2 used in RX ISR is connected to this pin         //
#define INVALID_RX_DATA_VALUE       0xA5                    // Used to invalidate RX message data content           //
#define INVALID_ID_VALUE            (uint32)0xFFFFFFFF      // Used to invalidate RX message ID value               //

#define TX_DATA_LOW_WORD            (uint32)0xbbaa9988      // Define CAN data lower word to be transmitted         //
#define TX_DATA_HIGH_WORD           (uint32)0xffeeddcc      // Define CAN data higher word to be transmitted        //
#define MAXIMUM_CAN_DATA_PAYLOAD    2                       // Define maximum classical CAN payload in 4-byte words //

#define CAN0 0
#define CAN1 1
#define CAN2 2
#define CAN3 3
#define CAN4 4

#define ISR_PRIORITY_GPT12_TIMER    6                       // Define the GPT12 Timer interrupt priority            //
#define ISR_PROVIDER_GPT12_TIMER    IfxSrc_Tos_cpu0         // Interrupt provider                                   //
#define RELOAD_VALUE                48828u                  // Reload value to have an interrupt each 500ms         //
*/



/*********************************************************************************************************************/
/*--------------------------------------------------Data Structures--------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    IfxCan_Can_Config canConfig;                            /* CAN module configuration structure                   */
    IfxCan_Can canModule;                                   /* CAN module handle                                    */
    IfxCan_Can_Node canSrcNode;                             /* CAN source node handle data structure                */
    IfxCan_Can_Node canTxNode;                             /* CAN source node handle data structure                */
    IfxCan_Can_Node canDstNode;                             /* CAN destination node handle data structure           */
    IfxCan_Can_Node canDst2Node;                            /* CAN destination2 node handle data structure          */
    IfxCan_Can_NodeConfig canNodeConfig;                    /* CAN node configuration structure                     */
    IfxCan_Filter canFilter;                                /* CAN filter configuration structure                   */
    IfxCan_Message txMsg;                                   /* Transmitted CAN message structure                    */
    IfxCan_Message rxMsg[NUMBER_OF_CAN_MESSAGES];               /* Received CAN message structure                    */
    uint32 txData[MAXIMUM_DATA_PAYLOAD_WORDS];                  /* Transmitted CAN data array                        */
    uint32 rxData[NUMBER_OF_CAN_MESSAGES][MAXIMUM_DATA_PAYLOAD_WORDS];    /* Received CAN data matrix                */
} McmcanType;

typedef struct
{
  uint32 rxData[255][2];    /* Received CAN data matrix                */
} Can_ReciveData_Type;

typedef struct{
        McmcanType *Can_Ch;
        Ifx_CAN *Can_Module;
        IfxCan_NodeId Node;
        Ifx_Priority Tx_Priority;
        Ifx_Priority Rx_Priority[3];
        IfxCan_InterruptLine Tx_InterruptLine;
        IfxCan_InterruptLine Rx_InterruptLine[3];
        IfxCan_Can_Pins pins;
        IfxCan_Filter *Filter_Std_Cfg;
        uint8 Filter_Std_Num;
        IfxCan_Filter *Filter_Ext_Cfg;
        uint8 Filter_Ext_Num;
        uint8 Can_num;
}Can_Node_Info;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

void Can_init(Can_Node_Info *Can_Info);
//uint8 transmitCanMessage(uint8 can_sel, uint32 can_id);
//uint8 CanMessage(McmcanType *g_mcmcan_sel,uint8 Can_num);


#endif /* MCMCAN_H_ */
#endif /* APPL_CAN_CAN_H_ */
