/**********************************************************************************************************************
 * \file I2c.h
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#ifndef I2C_H_
#define I2C_H_

#include "IfxI2c_I2c.h"
#include "../Port/PORT_cfg.h"
#include "../GPT12/GPT12_Timer_Interrupt.h"


//#define GPIO_I2C_Enable

/*********************************************************************************************************************/
/*-------------------------------------------------Structer define--------------------------------------------------*/
/*********************************************************************************************************************/

#define length_1byte 1
#define length_2byte 2
#define length_3byte 3
#define length_4byte 4
#define length_5byte 5
#define length_6byte 6

typedef struct
{
    PORT_PIN_Info *scl;
    PORT_PIN_Info *sda;
    IfxPort_PadDriver padDriver;
} GpioI2c_Pins;

typedef struct{
        IfxI2c_I2c *Channel;
        IfxI2c_I2c_Device *Device ;
        uint8 Addr ;
        IFX_CONST GpioI2c_Pins *pins;           /**< \brief Pins */
}i2c_Configuration;

union TI_Data_type {
    float type_float;
    signed int type_uint32;
};
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

void init_I2C0_module(IfxI2c_I2c *Dev_Ch,IfxI2c_Pins *I2C_MCP_PINS,float32 BaudRate);
void init_I2C1_module(IfxI2c_I2c *Dev_Ch,IfxI2c_Pins *I2C_MCP_PINS,float32 BaudRate);
void SetI2cDevinfo(i2c_Configuration *Dev_ID,IfxI2c_I2c *Dev_Ch,IfxI2c_I2c_Device *Dev_tag,uint8 Dev_Addr,GpioI2c_Pins *Pins);
void init_I2C_module_addr(i2c_Configuration *Dev_ID);


#endif /* I2C_H_ */









