/**********************************************************************************************************************
 * \file I2c.c
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
//#include "Ifx_Types.h"
//#include "IfxCpu.h"
//#include "IfxScuWdt.h"
//#include "string.h"
//#include "stdio.h"
#include "I2c.h"


/**********************************************************************************************************************
 *
 * Runnable Entity Name: init_I2C0_module
 *
**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of documentation area >>                  DO NOT CHANGE THIS COMMENT!
 * Symbol: I2c.c
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of documentation area >>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

void init_I2C0_module(IfxI2c_I2c *Dev_Ch,IfxI2c_Pins *I2C_MCP_PINS,float32 BaudRate)
{
    IfxI2c_I2c_Config i2cConfig;
    IfxI2c_I2c_initConfig(&i2cConfig, &MODULE_I2C0);
    i2cConfig.pins = I2C_MCP_PINS;
    i2cConfig.baudrate = BaudRate;

    IfxI2c_I2c_initModule(Dev_Ch, &i2cConfig);
}

/**********************************************************************************************************************
 *
 * Runnable Entity Name: init_I2C1_module
 *
**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of documentation area >>                  DO NOT CHANGE THIS COMMENT!
 * Symbol: I2c.c
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of documentation area >>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
void init_I2C1_module(IfxI2c_I2c *Dev_Ch,IfxI2c_Pins *I2C_MCP_PINS,float32 BaudRate)
{
    IfxI2c_I2c_Config i2cConfig;
    IfxI2c_I2c_initConfig(&i2cConfig, &MODULE_I2C1);
    i2cConfig.pins = I2C_MCP_PINS;
    i2cConfig.baudrate = BaudRate;

    IfxI2c_I2c_initModule(Dev_Ch, &i2cConfig);
}

/**********************************************************************************************************************
 *
 * Runnable Entity Name: SetI2cDevinfo
 *
**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of documentation area >>                  DO NOT CHANGE THIS COMMENT!
 * Symbol: I2c.c
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of documentation area >>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

void SetI2cDevinfo(i2c_Configuration *Dev_ID,IfxI2c_I2c *Dev_Ch,IfxI2c_I2c_Device *Dev_tag,uint8 Dev_Addr,GpioI2c_Pins *Pins)
{
    Dev_ID->Channel = Dev_Ch;
    Dev_ID->Device =  Dev_tag;
    Dev_ID->Addr = Dev_Addr;
    Dev_ID->pins =Pins;
}

/**********************************************************************************************************************
 *
 * Runnable Entity Name: init_I2C_module_addr
 *
**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of documentation area >>                  DO NOT CHANGE THIS COMMENT!
 * Symbol: I2c.c
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of documentation area >>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


void init_I2C_module_addr(i2c_Configuration *Dev_ID)
{
    // device의 정보(IfxI2c_I2c_Device 구조체) 에 사용할 i2c 포트 및 deviece 주소 /주소모드(기본 7bit)/speed 정보 구성 함수

    // Initialize device //
    IfxI2c_I2c_deviceConfig i2cDeviceConfig;                         // Create device configuration
    IfxI2c_I2c_initDeviceConfig(&i2cDeviceConfig, Dev_ID->Channel);    // Fill structure with default values and I2C

    // Because it is 7 bit long and bit 0 is R/W bit, the device address has to be shifted by 1
    i2cDeviceConfig.deviceAddress = Dev_ID->Addr << 1;
    IfxI2c_I2c_initDevice(Dev_ID->Device,&i2cDeviceConfig);       // Initialize the I2C device handle
}


















