/**********************************************************************************************************************
 * \file I2C_GPIO.h
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - none
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#ifndef I2C_GPIO_H
#define I2C_GPIO_H

#include "../Port/PORT_cfg.h"
#include "../GPT12/GPT12_Timer_Interrupt.h"
#include <string.h>
#include "I2c.h"

void GpioI2c_initSclSdaPin(GpioI2c_Pins *Pins);
void GpioI2c_I2c_start(i2c_Configuration *I2c_device);
void GpioI2c_I2c_stop(i2c_Configuration *I2c_device);
uint8 GpioI2c_I2c_write_Byte(i2c_Configuration *I2c_device, uint8 *Tx_Data,uint8 Length);
uint8 GpioI2c_I2c_write(i2c_Configuration *I2c_device, uint8 *Tx_Data,uint8 Length);
uint8 GpioI2c_I2c_read(i2c_Configuration *I2c_device, uint8 *Rx_Data,uint8 Length);

//void read_word(GpioI2c_I2c *I2c_Module, uint8 Taget_ID, uint8 RG, uint8 *Rx_Data,uint8 length);

#endif



