/**********************************************************************************************************************
 * \file I2C_cfg.c
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include <I2C_cfg.h>

/*********************************************************************************************************************/
/*-------------------------------------------------variable Section --------------------------------------------------*/

/*-----------------------------------------------I2C Channel--------------------------------------------------*/
IfxI2c_I2c I2c_Ch0;
IfxI2c_I2c I2c_Ch1;

Ifx_I2C I2C0_Gpio;
Ifx_I2C I2C1_Gpio;

/*********************************************************************************************************************/
/*-------------------------------------------------I2C_PINS--------------------------------------------------*/
/*********************************************************************************************************************/

IfxI2c_Pins I2C0_MCP_PINS =
{
        &I2C0_SCL_PIN,
        &I2C0_SDA_PIN,
        IfxPort_PadDriver_ttlSpeed1
};

IfxI2c_Pins I2C1_MCP_PINS =
{
        &I2C1_SCL_PIN,
        &I2C1_SDA_PIN,
        IfxPort_PadDriver_ttlSpeed1
};

GpioI2c_Pins i2c_Module1_PINS =
{
        &DioConf_DioChannel_11_13, //SDA
        &DioConf_DioChannel_11_14, //SCL
        IfxPort_PadDriver_ttlSpeed4
};

GpioI2c_Pins i2c_Module0_PINS =
{
        &DioConf_DioChannel_13_1, //SCL
        &DioConf_DioChannel_13_2, //SDA
        IfxPort_PadDriver_ttlSpeed4
};




/*-----------------------------------------------------I2cCh0-------------------------------------------------------*/
/*-------------------------------------------------I2cCh0_TCA9548-1-------------------------------------------------*/
i2c_Configuration I2cConf_I2cCh0_TCA9548_ADDR_0x70;
IfxI2c_I2c_Device Dev_I2cCh0_TCA9548_ADDR_0x70;
/*-------------------------------------------------I2cCh0_INA226 ---------------------------------------------------*/
i2c_Configuration I2cConf_I2cCh0_INA226_ADDR_0x40;
IfxI2c_I2c_Device Dev_I2cCh0_INA226_ADDR_0x40;
/*-------------------------------------------------I2cCh0_STS31A ---------------------------------------------------*/
i2c_Configuration I2cConf_I2cCh0_STS31A_ADDR_0x4A;
IfxI2c_I2c_Device Dev_I2cCh0_STS31A_ADDR_0x4A;
/*------------------------------------------------I2cCh0_TCA9548-2--------------------------------------------------*/
i2c_Configuration I2cConf_I2cCh0_TCA9548_ADDR_0x71;
IfxI2c_I2c_Device Dev_I2cCh0_TCA9548_ADDR_0x71;
/*-------------------------------------------------I2cCh0_STS31A ---------------------------------------------------*/
i2c_Configuration I2cConf_I2cCh0_STS31A_ADDR_0x4B;
IfxI2c_I2c_Device Dev_I2cCh0_STS31A_ADDR_0x4B;
/*------------------------------------------------------------------------------------------------------------------*/


/*-----------------------------------------------------I2cCh1-------------------------------------------------------*/
/*-------------------------------------------------I2cCh1_TCA9548 --------------------------------------------------*/

/*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*/


void I2c_Init(void){

    /*-----------------------------------------------------I2cCh0---------------------------------------------------*/
#ifdef GPIO_I2C_Enable
    I2c_Ch0.i2c=&I2C0_Gpio;
    I2c_Ch0.baudrate=I2C_BAUDRATE;
    GpioI2c_initSclSdaPin(&i2c_Module0_PINS);
#else
    init_I2C0_module(&I2c_Ch0, &I2C0_MCP_PINS, I2C_BAUDRATE);
#endif
    SetI2cDevinfo(&I2cConf_I2cCh0_TCA9548_ADDR_0x70, &I2c_Ch0, &Dev_I2cCh0_TCA9548_ADDR_0x70, 0x70,&i2c_Module0_PINS);
    init_I2C_module_addr(&I2cConf_I2cCh0_TCA9548_ADDR_0x70);

    SetI2cDevinfo(&I2cConf_I2cCh0_INA226_ADDR_0x40, &I2c_Ch0, &Dev_I2cCh0_INA226_ADDR_0x40, 0x40,&i2c_Module0_PINS);
    init_I2C_module_addr(&I2cConf_I2cCh0_INA226_ADDR_0x40);

    SetI2cDevinfo(&I2cConf_I2cCh0_STS31A_ADDR_0x4A, &I2c_Ch0, &Dev_I2cCh0_STS31A_ADDR_0x4A, 0x4A,&i2c_Module0_PINS);
    init_I2C_module_addr(&I2cConf_I2cCh0_STS31A_ADDR_0x4A);

    SetI2cDevinfo(&I2cConf_I2cCh0_TCA9548_ADDR_0x71, &I2c_Ch0, &Dev_I2cCh0_TCA9548_ADDR_0x71, 0x71,&i2c_Module0_PINS);
    init_I2C_module_addr(&I2cConf_I2cCh0_TCA9548_ADDR_0x71);

    SetI2cDevinfo(&I2cConf_I2cCh0_STS31A_ADDR_0x4B, &I2c_Ch0, &Dev_I2cCh0_STS31A_ADDR_0x4B, 0x4B,&i2c_Module0_PINS);
    init_I2C_module_addr(&I2cConf_I2cCh0_STS31A_ADDR_0x4B);
    /*-----------------------------------------------------I2cCh1---------------------------------------------------*/
#ifdef GPIO_I2C_Enable
    I2c_Ch1.i2c=&I2C1_Gpio;
    I2c_Ch1.baudrate=I2C_BAUDRATE;
    GpioI2c_initSclSdaPin(&i2c_Module1_PINS);
#else
    init_I2C1_module(&I2c_Ch1, &I2C1_MCP_PINS, I2C_BAUDRATE);
#endif


}
