/**********************************************************************************************************************
 * \file I2C_GPIO.c
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - none
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#include "I2C_GPIO.h"



void GpioI2c_initSclSdaPin(GpioI2c_Pins *Pins)
{
    IfxPort_OutputMode mode = (IfxPort_OutputMode)IfxPort_Mode_outputOpenDrainGeneral;
    IfxPort_setPinModeOutput(Pins->scl->Port, Pins->scl->Pin_Num, mode, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(Pins->sda->Port, Pins->sda->Pin_Num, mode, IfxPort_OutputIdx_general);
    IfxPort_setPinPadDriver(Pins->scl->Port, Pins->scl->Pin_Num, Pins->padDriver);
    IfxPort_setPinPadDriver(Pins->sda->Port, Pins->sda->Pin_Num, Pins->padDriver);
}



void GpioI2c_I2c_start(i2c_Configuration *I2c_device)
{

    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral);
    GPIO_SetPinMode(I2c_device->pins->scl,IfxPort_Mode_outputOpenDrainGeneral);  //Set SCL, SDA to output(Open Drain);


    GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high);
    GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);// Set SCL, SDA High

    //delay_us(1);
    delay_ns(500);
    GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_low);    // Clear SDA
    delay_ns(500);
    GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low);    // Clear SCL
    //delay_us(7);
}

void GpioI2c_I2c_stop(i2c_Configuration *I2c_device)
{
    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral);
    GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_low);                           // Clear SDA Low
    GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low);
    //delay_us(1); //delay 중요
    delay_ns(500);
    GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);    // Set SCL High
    delay_ns(500); //delay 중요
    GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high);    // Set SDA High

    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_inputNoPullDevice); // Set SDA to Input
}

uint8 Read_Ack[100];
uint32 Read_Ack_count=0;
uint8 GpioI2c_I2c_write_Byte(i2c_Configuration *I2c_device, uint8 *Tx_Data,uint8 Length)
{
    if(Read_Ack_count==0){
        memset(&Read_Ack[0],0xaa,100);
        }
    uint8 i = 0;
    uint8 Byte =0;
   // uint8 Read_Ack=0;
    uint8 buff[Length];
    memcpy(&buff[0],Tx_Data,Length);
    GpioI2c_I2c_start(I2c_device);

    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral); // Set SDA to output(Open Drain);
    for(Byte=0;Byte<Length;Byte++)
    {
        for (i = 0; i < 8 ; i++)
        {
            if((buff[Byte] & 0x80)==0x80)
            {
                GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high);    // Set SDA High
            }
            else
            {
                GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_low);    // Clear SDA
            }
            delay_ns(100);  // delay 중요
            GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);    // Set SCL High, Clock data
            delay_ns(500);  // delay 중요
            buff[Byte] = buff[Byte] << 1;   // Shift data in buffer right one
            GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low);        // Clear SCL
            delay_ns(500);  // delay 중요
        }

        GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_inputNoPullDevice); // Set SDA to Input

        GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);

        delay_ns(500);
        GPIO_GetPinState(I2c_device->pins->sda,&Read_Ack[Read_Ack_count]);
        Read_Ack_count++;
        GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low); //Clear SCL.
        delay_ns(500);

        GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high);    // Set SDA High
        GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral); // Set SDA to output(Open Drain);
        if(Read_Ack[Read_Ack_count]==1){
            buff[Byte] = Tx_Data[Byte];
            Byte--;
        }
    }

    if(Read_Ack_count>=100){
        Read_Ack_count=1;
    }
    //return Read_Ack;
        return FALSE;
}
uint8 Tx_buff[256];
uint8 GpioI2c_I2c_write(i2c_Configuration *I2c_device, uint8 *Tx_Data,uint8 Length)
{
    //uint8 Tx_buff[Length+1];
    Tx_buff[0]=(uint8)I2c_device->Device->deviceAddress;
    memcpy(&Tx_buff[1],Tx_Data,Length);
    GpioI2c_I2c_write_Byte(I2c_device,&Tx_buff[0],Length+1);
    GpioI2c_I2c_stop(I2c_device);

    return FALSE;

}

uint8 GpioI2c_I2c_read(i2c_Configuration *I2c_device, uint8 *Rx_Data,uint8 Length)
{
    uint8 i;
    uint8 Byte=0;
    uint8 buff[Length];
    uint8 Read_Gpio=0;
    memset(&buff[0],0x00,Length);
    uint8 Read_Taget_Addr;
    Read_Taget_Addr=((uint8)(I2c_device->Device->deviceAddress))|0x01;
    GpioI2c_I2c_write_Byte(I2c_device, &Read_Taget_Addr, 1);

    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_inputNoPullDevice); // Set SDA to Input

    for(Byte=0;Byte<Length;Byte++)
    {
        GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_inputNoPullDevice); // Set SDA to Input
        for(i=0; i<8; i++)
        {
            //delay_ns(10);
            GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);
            delay_ns(500);// Set SCL High, Clock bit out
            buff[Byte] <<= 1;

            // Read data on SDA pin
            GPIO_GetPinState(I2c_device->pins->sda,&Read_Gpio);
            if (Read_Gpio==STD_HIGH)
            {
                buff[Byte] |= 0x01;
            }
            GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low); // Clear SCL
            delay_ns(490);
        }

        GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral); // Set SDA to output(Open Drain);
        if(Byte==Length) //NACK
        {
            GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high); //SDA HIGH.
        }
        else //ACK.
        {
            GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_low); //SDA LOW.
        }
        GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_high);
        delay_ns(500);
        GPIO_SetPinState(I2c_device->pins->scl, IfxPort_State_low); //SCL LOW.
        delay_ns(500);
        //GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_inputNoPullDevice); // Set SDA to Input
        //delay_us(1);
        //delay_ns(500);

    }
    GPIO_SetPinState(I2c_device->pins->sda, IfxPort_State_high); //SDA HIGH.
    delay_ns(500);
    GPIO_SetPinMode(I2c_device->pins->sda,IfxPort_Mode_outputOpenDrainGeneral); // Set SDA to output(Open Drain);
    GpioI2c_I2c_stop(I2c_device);
    memcpy(Rx_Data,&buff[0],Length);

    return FALSE;
}
/*
void read_word(i2c_Configuration *I2c_device, uint8 Taget_ID, uint8 RG, uint8 *Rx_Data,uint8 length)
{

    unsigned char ucHibyte = 0;
    unsigned char ucLobyte = 0;

    uint8 Tx_buff[2];
    ucHibyte=0;
    ucLobyte=0;
    Tx_buff[0]=(Taget_ID<<0x01)|0x00;
    Tx_buff[1]=RG;
    GpioI2c_start(I2c_device);
    GpioI2c_Write_Byte(I2c_device,&Tx_buff[0],2);


    Tx_buff[0]=(Taget_ID<<0x01)|0x01;
    GpioI2c_start(I2c_device);
    GpioI2c_Write_Byte(I2c_device,&Tx_buff[0],1);

    GpioI2c_Read_Byte(I2c_device,Rx_Data,length);
    //ucHibyte=read_i2c_byte(1);

    GpioI2c_stop(I2c_device);
}
*/
/*
void write_word(unsigned char slave, unsigned char page_address, unsigned char index_address, unsigned char value)
{
    i2c_start();
    write_i2c_byte(slave);
    write_i2c_byte(page_address);
    write_i2c_byte(index_address);
    write_i2c_byte(value);
    i2c_stop();
}
*/

