/**********************************************************************************************************************
 * \file I2C_Device.h
 * \copyright Copyright (C)
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------include Section--------------------------------------------------*/
/*********************************************************************************************************************/
#include "I2c.h"
#include "I2c_Device.h"
#include "I2C_GPIO.h"


/*********************************************************************************************************************/
/*-------------------------------------------------define Section --------------------------------------------------*/
/*********************************************************************************************************************/
#define I2C_BAUDRATE                252446                      // 400 kHz baud rate

#define I2C0_SCL_PIN            IfxI2c0_SCL_P13_1_INOUT     // SCL PIN
#define I2C0_SDA_PIN            IfxI2c0_SDA_P13_2_INOUT     // SDA PIN
#define I2C1_SCL_PIN            IfxI2c1_SCL_P13_9_INOUT     // SCL PIN
#define I2C1_SDA_PIN            IfxI2c1_SDA_P13_12_INOUT    // SDA PIN

/*********************************************************************************************************************/
/*-----------------------------------------------I2C Channel define--------------------------------------------------*/
/*********************************************************************************************************************/
extern IfxI2c_I2c I2c_Ch0;
extern IfxI2c_I2c I2c_Ch1;


/*********************************************************************************************************************/
/*-------------------------------------------------variable Section --------------------------------------------------*/
/*********************************************************************************************************************/

/*-----------------------------------------------------I2cCh0-------------------------------------------------------*/
/*-------------------------------------------------I2cCh0_TCA9548 --------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_TCA9548_ADDR_0x70;
/*-------------------------------------------------I2cCh0_INA226 ---------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_INA226_ADDR_0x40;
/*-------------------------------------------------I2cCh0_STS31A-1 ---------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_STS31A_ADDR_0x4A;
/*-------------------------------------------------I2cCh1_TCA9548 --------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_TCA9548_ADDR_0x71;
/*-------------------------------------------------I2cCh0_STS31A-2 ---------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_STS31A_ADDR_0x4B;

/*-------------------------------------------------I2cCh0_MAX20087 ---------------------------------------------------*/
extern i2c_Configuration I2cConf_I2cCh0_MAX20087_ADDR_0x28;
extern IfxI2c_I2c_Device Dev_I2cCh0_MAX20087_ADDR_0x28;

extern i2c_Configuration I2cConf_I2cCh0_MAX20087_ADDR_0x29;
extern IfxI2c_I2c_Device Dev_I2cCh0_MAX20087_ADDR_0x29;
/*------------------------------------------------------------------------------------------------------------------*/

/*-----------------------------------------------------I2cCh1-------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------------------------*/


void I2c_Init(void);





















